spring:
  application:
    name: buckpal
  jpa:
    database: h2
    show-sql: false
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
buckpal:
  transferThreshold: 10000